---
#
# Ansible managed
#
repository:
  description: Install and configure libvirt on your system.
  homepage: https://robertdebock.nl/
  topics: libvirt, ansible, molecule, tox, playbook, hacktoberfest
