---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="fedora" tag="rawhide"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - function retry { counter=0 ; until "$@" ; do exit=$? ; counter=$(($counter + 1)) ; if [ $counter -ge 3 ] ; then return $exit ; fi ; done ; return 0; } ; retry tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "YBRkVozvPF7C+b6Q1v/zigpVzz1+BZt2bZE+cqRRD/wzwNONYW3Iorv5RoYl1cc8NyqbvjDYTtnXb/hlfM2qt+0NhtkSzH/lYwaC0bRV3GTY5FDHcDe41P+9kvPpLhZKS+QzGpDf5DOAI/qBZuSVKyNJ90fdoGJogo58Eqxf5+VbP/6juD0fApADwOSI89SRmZub1koCRJwhU2QfqOZyzKFiLVEeyOIKgw5cqlZdhC6FBlP38RQzFVe9Zbf4n7A4X95GYYKpuyzpH2/kdm5GTK8eLTxB/877zXv647VtrcVHwdrsPyM9LiTKNfPR70VVqXIsrpGBAUDU6OIopYEuaLd6V2L5d1UCX9ZPTmq7zk/QtOGFhFZiTESmsWXNFNydOaS16u5SS81TEGgI7UeeBABg7Gqq7PvKkj/S8ZOfmx69IrHN6mngkVYieZ8ElP8yUrAz4+yJy7GUQ/4nGwJ3YyerwxJgo4g8Du4DBQ79bek/z3+oJVKQh/LEjpTitLU4ucDR0AtVlv4aN5jWEzvPy7xyuPvqsjygXFNyGda8Mu5XgbBn4c+EauG05qDI35C7sIpVcT/gCezO3Y67IxmmbTtnnMXCwe5KMySp+j/mLjKctAu7h7f9yBkH9usVPZNKdG5oMBttUhJuBAR5UkeT6tonB0K1arOx9CG1FU7qiNo="
  email: false
