---
# tasks file for libvirt

- name: Install libvirt
  ansible.builtin.package:
    name: "{{ libvirt_packages }}"
    state: present

- name: Start libvirtd
  ansible.builtin.service:
    name: "{{ libvirt_service }}"
    state: started
    enabled: yes
