---
# tasks file for libvirt

- name: install libvirt
  package:
    name: "{{ libvirt_packages }}"
    state: present

- name: start libvirtd
  service:
    name: "{{ libvirt_service }}"
    state: started
    enabled: yes
